'use client';

import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/common/PageHeader';
import { Card, CardContent } from '@/components/common/Card';
import { Badge } from '@/components/common/Badge';

export default function StrategiesPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/ai/strategy?tenant_id=demo-tenant')
      .then(r => r.json())
      .then(json => { if (json.success) setData(json.data); })
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="p-6"><PageHeader title="AI Strategies" description="Action plans generated by AI" /><p className="text-gray-500 mt-4">Loading...</p></div>;

  const strategies = data?.strategies || [];
  const stats = data?.stats || { total: 0, draft: 0, active: 0, completed: 0, avg_confidence: 0 };

  return (
    <div className="p-6 space-y-6">
      <PageHeader title="AI Strategies" description="Action plans generated and managed by AI" />

      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        <Card><CardContent className="p-4 text-center"><p className="text-xs text-gray-500">Total</p><p className="text-2xl font-bold">{stats.total}</p></CardContent></Card>
        <Card><CardContent className="p-4 text-center"><p className="text-xs text-gray-500">Draft</p><p className="text-2xl font-bold text-gray-600">{stats.draft}</p></CardContent></Card>
        <Card><CardContent className="p-4 text-center"><p className="text-xs text-gray-500">Active</p><p className="text-2xl font-bold text-blue-600">{stats.active}</p></CardContent></Card>
        <Card><CardContent className="p-4 text-center"><p className="text-xs text-gray-500">Completed</p><p className="text-2xl font-bold text-green-600">{stats.completed}</p></CardContent></Card>
        <Card><CardContent className="p-4 text-center"><p className="text-xs text-gray-500">Avg Confidence</p><p className="text-2xl font-bold">{stats.avg_confidence}%</p></CardContent></Card>
      </div>

      {strategies.length > 0 ? (
        <div className="space-y-4">
          {strategies.map((s: any) => (
            <Card key={s.id}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{s.title}</h3>
                    <Badge className={s.status === 'completed' ? 'bg-green-100 text-green-800' : s.status === 'executing' ? 'bg-blue-100 text-blue-800' : s.status === 'approved' ? 'bg-purple-100 text-purple-800' : 'bg-gray-100 text-gray-800'}>{s.status}</Badge>
                  </div>
                  <span className="text-sm text-gray-500">{s.confidence}% confidence</span>
                </div>
                {s.description && <p className="text-sm text-gray-600 mb-2">{s.description}</p>}
                <div className="flex gap-4 text-xs text-gray-400">
                  <span>Steps: {s.steps?.length || 0}</span>
                  <span>Impact: {s.estimated_impact}/100</span>
                  {s.estimated_duration_days && <span>Duration: ~{s.estimated_duration_days} days</span>}
                </div>
                {s.steps && s.steps.length > 0 && (
                  <div className="mt-3 flex flex-wrap gap-1">
                    {s.steps.map((step: any, i: number) => (
                      <Badge key={i} className="bg-blue-50 text-blue-700 text-xs">{step.title}</Badge>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card><CardContent className="p-8 text-center text-gray-500">No strategies yet. Strategies are generated automatically or manually created.</CardContent></Card>
      )}
    </div>
  );
}