'use client';

import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/common/PageHeader';
import { Card, CardContent } from '@/components/common/Card';
import { Badge } from '@/components/common/Badge';

export default function BriefingsPage() {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/ai/briefing?tenant_id=demo-tenant')
      .then(r => r.json())
      .then(json => { if (json.success) setData(Array.isArray(json.data) ? json.data : json.data ? [json.data] : []); })
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="p-6"><PageHeader title="AI Briefings" description="Daily operations summaries" /><p className="text-gray-500 mt-4">Loading...</p></div>;

  return (
    <div className="p-6 space-y-6">
      <PageHeader title="AI Briefings" description="Daily operations summaries generated by AI" />

      {data.length > 0 ? (
        <div className="space-y-4">
          {data.map((b: any) => (
            <Card key={b.id}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{b.title}</h3>
                    <Badge className="bg-blue-100 text-blue-800">{b.period}</Badge>
                  </div>
                  <span className="text-sm text-gray-400">{new Date(b.date).toLocaleDateString()}</span>
                </div>

                <p className="text-gray-700 mb-3 whitespace-pre-line">{b.summary}</p>

                {b.highlights && b.highlights.length > 0 && (
                  <div className="mb-3">
                    <p className="text-xs font-medium text-gray-500 mb-1">Highlights</p>
                    <div className="flex flex-wrap gap-2">
                      {b.highlights.map((h: any, i: number) => (
                        <Badge key={i} className="bg-green-50 text-green-700">{h.text}</Badge>
                      ))}
                    </div>
                  </div>
                )}

                {b.alerts && b.alerts.length > 0 && (
                  <div className="mb-3">
                    <p className="text-xs font-medium text-gray-500 mb-1">Alerts</p>
                    <div className="space-y-1">
                      {b.alerts.map((a: any, i: number) => (
                        <div key={i} className="flex items-center gap-2 text-sm">
                          <Badge className={a.severity === 'critical' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'}>{a.severity}</Badge>
                          <span>{a.title}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {b.recommendations && b.recommendations.length > 0 && (
                  <div>
                    <p className="text-xs font-medium text-gray-500 mb-1">Recommendations</p>
                    <div className="space-y-1">
                      {b.recommendations.map((r: any, i: number) => (
                        <div key={i} className="text-sm text-gray-600">• {r.title} (impact: {r.impact})</div>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card><CardContent className="p-8 text-center text-gray-500">No briefings yet. Briefings are generated daily.</CardContent></Card>
      )}
    </div>
  );
}